### ISSUE TITLE
How to reproduce the 6D pose tracking results on NOCS-REAL

### ISSUE THREAD

**Issue by Michaelswitch** [THU-DA-6D-Pose-Group/CATRE#11]
Hi, thanks for releasing the great work. How to reproduce the 6D pose tracking results on NOCS-REAL? We are now only able to reproduce the 6D pose refinement results.

**Comment by shanice-l** [comment]
Yes. I only provide the code for refinement. That's because the tracking code is somehow dirty :) (I do not clean it, so there are many redundant code).  
You can try to implement tracking by yourself. It's very easy. Just replace the init_pose with the last frame's pose. I use the same model weights for both refinement and tracking. So you can directly run it without any re-training.
