### ISSUE TITLE
Any plan to share the ttrained weights and testing code on CAMERA25?

### ISSUE THREAD

**Issue by Lynne-Zheng-Linfang** [THU-DA-6D-Pose-Group/CATRE#5]
Hi, thanks for sharing the code. Is there any plan to share the trained weights and testing code on CAMERA25? Thanks.

**Comment by shanice-l** [comment]
Since the experiments on the synthetic dataset are not as vital as the real one, we didn't release the code and weights.

You can easily get the results on CAMERA25 by modifying the  [dataset file](https://github.com/THU-DA-6D-Pose-Group/CATRE/blob/main/core/catre/datasets/nocs.py) and [config file](https://github.com/THU-DA-6D-Pose-Group/CATRE/blob/main/configs/catre/NOCS_REAL/aug05_kpsMS_r9d_catreDisR_shared_tspcl_convPerRot_scaleexp_120e.py).
